#!/usr/bin/env bash

# $1 -> relative url i.e /feed/posts, $2 -> stringified json data
arg1_url=$1
arg2_auth=$2
curl -X POST "http://localhost:3000$arg1_url" -d @data.json -H "Content-Type: application/json" -H "Authorization: $arg2_auth" | jq
