#!/usr/bin/env bash

# $1 -> relative url i.e /feed/posts, $2 -> stringified json data
arg1_url=$1
# arg3_auth=$2

echo $arg2_data
curl -X PUT "http://localhost:3000$arg1_url" -d @data.json -H "Content-Type: application/json" | jq
echo; #Authorization: $arg3_auth
